import type { SellSideListCandidate, PartialCandidate } from './types'

export const SEED_CANDIDATES: SellSideListCandidate[] = [
  {
    institution: 'Bank of America',
    listName: 'Fab Five Software Stocks for H2 2026',
    displayName: 'Bank of America Fab Five Software Stocks for H2 2026',
    period: 'H2 2026',
    year: 2026,
    theme: 'Infrastructure software',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'SNOW', action: 'buy' },
      { ticker: 'DDOG', action: 'buy' },
      { ticker: 'FROG', action: 'buy' },
      { ticker: 'MDB', action: 'buy' },
      { ticker: 'TWLO', action: 'buy' },
    ],
  },
  {
    institution: 'Bank of America',
    listName: 'Top 10 U.S. Ideas for Q1 2026',
    displayName: 'Bank of America Top 10 U.S. Ideas Q1 2026',
    period: 'Q1 2026',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'AMZN', action: 'buy' },
      { ticker: 'BA', action: 'buy' },
      { ticker: 'CI', action: 'buy' },
      { ticker: 'CEG', action: 'buy' },
      { ticker: 'DG', action: 'buy' },
      { ticker: 'EQIX', action: 'buy' },
      { ticker: 'MRK', action: 'buy' },
      { ticker: 'SPOT', action: 'buy' },
      { ticker: 'VRTX', action: 'buy' },
      { ticker: 'LEN', action: 'underperform', note: 'Underperform / non-bullish' },
    ],
  },
  {
    institution: 'Bank of America',
    listName: 'Top H2 Tech / AI Stack Ideas',
    displayName: 'Bank of America Top H2 Tech / AI Stack Ideas',
    period: 'H2 2026',
    year: 2026,
    theme: 'AI Stack',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'NVDA', action: 'buy' },
      { ticker: 'META', action: 'buy' },
      { ticker: 'SNOW', action: 'buy' },
      { ticker: 'DT', action: 'buy' },
      { ticker: 'SNDK', action: 'buy' },
    ],
  },
  {
    institution: 'Bank of America',
    listName: 'Top 4 Biotech Stocks for 2026',
    displayName: 'Bank of America Top 4 Biotech Stocks for 2026',
    year: 2026,
    sector: 'Biotech',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'VRTX', action: 'buy' },
      { ticker: 'OCUL', action: 'buy' },
      { ticker: 'KALV', action: 'buy' },
      { ticker: 'ARGX', action: 'buy' },
    ],
  },
  {
    institution: 'Bank of America',
    listName: 'Top 6 Chip Stocks for 2026',
    displayName: 'Bank of America Top 6 Chip Stocks for 2026',
    year: 2026,
    sector: 'Semiconductors',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'NVDA', action: 'buy' },
      { ticker: 'AVGO', action: 'buy' },
      { ticker: 'LRCX', action: 'buy' },
      { ticker: 'KLAC', action: 'buy' },
      { ticker: 'ADI', action: 'buy' },
      { ticker: 'CDNS', action: 'buy' },
    ],
  },
  {
    institution: 'Bank of America',
    listName: 'Paper & Packaging Stocks for 2026',
    displayName: 'Bank of America Paper & Packaging Stocks for 2026',
    year: 2026,
    sector: 'Paper & Packaging',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'BALL', action: 'buy' },
      { ticker: 'SLGN', action: 'buy' },
      { ticker: 'SON', action: 'buy' },
      { ticker: 'PKG', action: 'buy' },
    ],
  },
  {
    institution: 'Bank of America',
    listName: 'Private Credit / Alternative Asset Manager Buy List',
    displayName: 'Bank of America Private Credit / Alternative Asset Manager Buy List',
    year: 2026,
    sector: 'Alternative Assets',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'ARES', action: 'buy' },
      { ticker: 'KKR', action: 'buy' },
      { ticker: 'OWL', action: 'buy' },
      { ticker: 'BX', action: 'buy' },
    ],
  },
  {
    institution: 'Bank of America',
    listName: 'AI Data-Center Utilities / Energy Stocks',
    displayName: 'Bank of America AI Data-Center Utilities / Energy Stocks',
    year: 2026,
    theme: 'AI Data Center',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'PEG', action: 'buy' },
      { ticker: 'LNT', action: 'buy' },
      { ticker: 'SRE', action: 'buy' },
      { ticker: 'SWX', action: 'buy' },
      { ticker: 'XEL', action: 'buy' },
    ],
  },
  {
    institution: 'Bank of America',
    listName: 'Metals & Mining Top Picks',
    displayName: 'Bank of America Metals & Mining Top Picks',
    year: 2026,
    sector: 'Metals & Mining',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'AEM', action: 'buy' },
      { ticker: 'CCJ', action: 'buy' },
      { ticker: 'FCX', action: 'buy' },
    ],
  },
  {
    institution: 'Morgan Stanley',
    listName: 'Best Application Software Stocks for 2026',
    displayName: 'Morgan Stanley Best Application Software Stocks for 2026',
    year: 2026,
    sector: 'Application software',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'HUBS', action: 'buy' },
      { ticker: 'KVYO', action: 'buy' },
      { ticker: 'WIX', action: 'buy' },
      { ticker: 'AMPL', action: 'buy' },
      { ticker: 'BL', action: 'buy' },
      { ticker: 'DSGX', action: 'buy' },
      { ticker: 'NAVN', action: 'buy' },
    ],
  },
  {
    institution: 'Morgan Stanley',
    listName: 'AI-Hit Software Stocks to Buy on Discount',
    displayName: 'Morgan Stanley AI-Hit Software Stocks to Buy on Discount',
    year: 2026,
    theme: 'AI-hit software rebound',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'MSFT', action: 'buy' },
      { ticker: 'INTU', action: 'buy' },
      { ticker: 'CRM', action: 'buy' },
      { ticker: 'NOW', action: 'buy' },
      { ticker: 'PANW', action: 'buy' },
      { ticker: 'SHOP', action: 'buy' },
      { ticker: 'TEAM', action: 'buy' },
      { ticker: 'NET', action: 'buy' },
      { ticker: 'SNOW', action: 'buy' },
    ],
  },
  {
    institution: 'Morgan Stanley',
    listName: 'Strait of Hormuz / Lower Oil Reopening Basket',
    displayName: 'Morgan Stanley Strait of Hormuz / Lower Oil Reopening Basket',
    year: 2026,
    theme: 'Reopening',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'BKNG', action: 'buy' },
      { ticker: 'CHWY', action: 'buy' },
      { ticker: 'HAS', action: 'buy' },
      { ticker: 'W', action: 'buy' },
      { ticker: 'C', action: 'buy' },
      { ticker: 'MA', action: 'buy' },
      { ticker: 'STT', action: 'buy' },
      { ticker: 'ZION', action: 'buy' },
      { ticker: 'JCI', action: 'buy' },
      { ticker: 'TT', action: 'buy' },
      { ticker: 'ROK', action: 'buy' },
    ],
  },
  {
    institution: 'Morgan Stanley',
    listName: 'North American IT Hardware Outlook / High-Conviction Ideas',
    displayName: 'Morgan Stanley North American IT Hardware Outlook / High-Conviction Ideas',
    year: 2026,
    sector: 'IT Hardware',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'AAPL', action: 'buy' },
      { ticker: 'DELL', action: 'buy' },
      { ticker: 'TDC', action: 'buy' },
      { ticker: 'WDC', action: 'buy' },
      { ticker: 'STX', action: 'buy' },
      { ticker: 'SNX', action: 'buy' },
      { ticker: 'HPE', action: 'buy' },
    ],
  },
  {
    institution: 'UBS',
    listName: 'Top 10 Highest-Conviction Stock Picks for 2026',
    displayName: 'UBS Top 10 Highest-Conviction Stock Picks for 2026',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'ACAD', action: 'buy' },
      { ticker: 'LNT', action: 'buy' },
      { ticker: 'AMZN', action: 'buy' },
      { ticker: 'AMT', action: 'buy' },
      { ticker: 'COF', action: 'buy' },
      { ticker: 'PEP', action: 'buy' },
      { ticker: 'DECK', action: 'buy' },
      { ticker: 'GM', action: 'buy' },
      { ticker: 'OVV', action: 'buy' },
      { ticker: 'WWD', action: 'buy' },
    ],
  },
  {
    institution: 'UBS',
    listName: '12 Tech, Media, and Telecom High-Conviction Picks',
    displayName: 'UBS 12 Tech, Media, and Telecom High-Conviction Picks',
    year: 2026,
    sector: 'TMT',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'AMZN', action: 'buy' },
      { ticker: 'PLTR', action: 'buy' },
      { ticker: 'FROG', action: 'buy' },
      { ticker: 'TWLO', action: 'buy' },
      { ticker: 'ACN', action: 'buy' },
      { ticker: 'NFLX', action: 'buy' },
      { ticker: 'AMT', action: 'buy' },
      { ticker: 'GBTG', action: 'buy' },
      { ticker: 'MA', action: 'buy' },
      { ticker: 'GLBE', action: 'buy' },
      { ticker: 'ENTG', action: 'buy' },
      { ticker: 'ANET', action: 'buy' },
    ],
  },
  {
    institution: 'UBS',
    listName: '10 Apparel Stock Picks for 2026',
    displayName: 'UBS 10 Apparel Stock Picks for 2026',
    year: 2026,
    sector: 'Apparel',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'RL', action: 'buy' },
      { ticker: 'ONON', action: 'buy' },
      { ticker: 'GIL', action: 'buy' },
      { ticker: 'LEVI', action: 'buy' },
      { ticker: 'AS', action: 'buy' },
      { ticker: 'BIRK', action: 'buy' },
      { ticker: 'TJX', action: 'buy' },
      { ticker: 'BURL', action: 'buy' },
      { ticker: 'DECK', action: 'buy' },
      { ticker: 'SIG', action: 'buy' },
    ],
  },
  {
    institution: 'UBS',
    listName: '8 Industrials Stocks With 20%+ Upside',
    displayName: 'UBS 8 Industrials Stocks With 20%+ Upside',
    year: 2026,
    sector: 'Industrials',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'PWR', action: 'buy' },
      { ticker: 'ESI', action: 'buy' },
      { ticker: 'CHRW', action: 'buy' },
      { ticker: 'BA', action: 'buy' },
      { ticker: 'CTAS', action: 'buy' },
      { ticker: 'GEV', action: 'buy' },
      { ticker: 'UAL', action: 'buy' },
      { ticker: 'WMS', action: 'buy' },
    ],
  },
  {
    institution: 'Citi',
    listName: 'Large Cap Recommended List - 2026 Additions',
    displayName: 'Citi Large Cap Recommended List - 2026 Additions',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'MCHP', action: 'buy' },
      { ticker: 'USB', action: 'buy' },
      { ticker: 'AFRM', action: 'buy' },
      { ticker: 'DAL', action: 'buy' },
      { ticker: 'TMO', action: 'buy' },
      { ticker: 'BA', action: 'buy' },
      { ticker: 'AVGO', action: 'buy' },
      { ticker: 'LIN', action: 'buy' },
      { ticker: 'LRCX', action: 'buy' },
      { ticker: 'MDT', action: 'buy' },
      { ticker: 'FE', action: 'buy' },
    ],
  },
  {
    institution: 'Citi',
    listName: 'Back-Office Software Top Picks',
    displayName: 'Citi Back-Office Software Top Picks',
    period: 'June 2026',
    year: 2026,
    sector: 'Application software',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'BOX', action: 'buy' },
      { ticker: 'NAVN', action: 'buy' },
      { ticker: 'APPN', action: 'buy' },
    ],
  },
  {
    institution: 'Jefferies',
    listName: 'Top Software Stocks for 2026',
    displayName: 'Jefferies Top Software Stocks for 2026',
    year: 2026,
    sector: 'Software',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'ADP', action: 'buy' },
      { ticker: 'NOW', action: 'buy' },
      { ticker: 'HUBS', action: 'buy' },
      { ticker: 'SHOP', action: 'buy' },
      { ticker: 'TWLO', action: 'buy' },
      { ticker: 'TOST', action: 'buy' },
    ],
  },
  {
    institution: 'Jefferies',
    listName: 'Biotech Top 6 for 2026',
    displayName: 'Jefferies Biotech Top 6 for 2026',
    year: 2026,
    sector: 'Biotech',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'SLDB', action: 'buy' },
      { ticker: 'DNTH', action: 'buy' },
      { ticker: 'ORIC', action: 'buy' },
      { ticker: 'TNGX', action: 'buy' },
      { ticker: 'TSHA', action: 'buy' },
      { ticker: 'TYRA', action: 'buy' },
    ],
  },
  {
    institution: 'Jefferies',
    listName: 'Aerospace & Defense Favorite Picks',
    displayName: 'Jefferies Aerospace & Defense Favorite Picks',
    year: 2026,
    sector: 'Aerospace & Defense',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'BA', action: 'buy' },
      { ticker: 'LHX', action: 'buy' },
      { ticker: 'LDOS', action: 'buy' },
      { ticker: 'FTAI', action: 'buy' },
      { ticker: 'HWM', action: 'buy' },
      { ticker: 'LOAR', action: 'buy' },
    ],
  },
  {
    institution: 'Jefferies',
    listName: 'AI-Panic Discount Bin Winners',
    displayName: 'Jefferies AI-Panic Discount Bin Winners',
    year: 2026,
    theme: 'AI Panic Rebound',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'SLM', action: 'buy' },
      { ticker: 'LNC', action: 'buy' },
      { ticker: 'EQH', action: 'buy' },
      { ticker: 'MSFT', action: 'buy' },
      { ticker: 'COF', action: 'buy' },
      { ticker: 'META', action: 'buy' },
      { ticker: 'NOW', action: 'buy' },
    ],
  },
  {
    institution: 'Jefferies',
    listName: 'AI-Scare Consumer Internet Winners',
    displayName: 'Jefferies AI-Scare Consumer Internet Winners',
    year: 2026,
    sector: 'Consumer Internet',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'ABNB', action: 'buy' },
      { ticker: 'CVNA', action: 'buy' },
      { ticker: 'DASH', action: 'buy' },
      { ticker: 'DIS', action: 'buy' },
      { ticker: 'ROKU', action: 'buy' },
      { ticker: 'SPOT', action: 'buy' },
    ],
  },
  {
    institution: 'Jefferies',
    listName: 'Franchise Picks Refresh',
    displayName: 'Jefferies Franchise Picks Refresh',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'AMZN', action: 'buy' },
      { ticker: 'APP', action: 'buy' },
      { ticker: 'CRDO', action: 'buy' },
      { ticker: 'MCD', action: 'buy' },
      { ticker: 'RDNT', action: 'buy' },
      { ticker: 'TMO', action: 'buy' },
      { ticker: 'ULS', action: 'buy' },
    ],
  },
  {
    institution: 'BTIG',
    listName: 'TMT Best Picks for 2026',
    displayName: 'BTIG TMT Best Picks for 2026',
    year: 2026,
    sector: 'Technology, Media, Telecom',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'MELI', action: 'buy' },
      { ticker: 'TKO', action: 'buy' },
      { ticker: 'TWLO', action: 'buy' },
      { ticker: 'ZS', action: 'buy' },
      { ticker: 'DKNG', action: 'buy' },
      { ticker: 'U', action: 'buy' },
      { ticker: 'COMP', action: 'buy' },
      { ticker: 'KVYO', action: 'buy' },
    ],
  },
  {
    institution: 'BTIG',
    listName: 'Financial Stocks for 1H 2026',
    displayName: 'BTIG Financial Stocks for 1H 2026',
    period: '1H 2026',
    year: 2026,
    sector: 'Financials',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'COF', action: 'buy' },
      { ticker: 'RITM', action: 'buy' },
      { ticker: 'ENVA', action: 'buy' },
      { ticker: 'XYZ', action: 'buy' },
      { ticker: 'FOUR', action: 'buy' },
      { ticker: 'RKT', action: 'buy' },
    ],
  },
  {
    institution: 'BTIG',
    listName: 'Energy & Infrastructure Picks',
    displayName: 'BTIG Energy & Infrastructure Picks',
    year: 2026,
    sector: 'Energy & Infrastructure',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'PPL', action: 'buy' },
      { ticker: 'RIOT', action: 'buy' },
      { ticker: 'SR', action: 'buy' },
      { ticker: 'CLSK', action: 'buy' },
    ],
  },
  {
    institution: 'BTIG',
    listName: 'Healthcare Stocks for 2026',
    displayName: 'BTIG Healthcare Stocks for 2026',
    year: 2026,
    sector: 'Healthcare',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'NKTR', action: 'buy' },
      { ticker: 'ALDX', action: 'buy' },
      { ticker: 'PVLA', action: 'buy' },
      { ticker: 'AVTX', action: 'buy' },
      { ticker: 'ESTA', action: 'buy' },
      { ticker: 'GH', action: 'buy' },
      { ticker: 'FHTX', action: 'buy' },
      { ticker: 'WGS', action: 'buy' },
      { ticker: 'LFST', action: 'buy' },
      { ticker: 'BTSG', action: 'buy' },
    ],
  },
  {
    institution: 'Evercore ISI',
    listName: 'Top 5 Retail Stocks for 2026',
    displayName: 'Evercore ISI Top 5 Retail Stocks for 2026',
    year: 2026,
    sector: 'Retail',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'AMZN', action: 'buy' },
      { ticker: 'GPC', action: 'buy' },
      { ticker: 'WMT', action: 'buy' },
      { ticker: 'HD', action: 'buy' },
      { ticker: 'ORLY', action: 'buy' },
    ],
  },
  {
    institution: 'JPMorgan',
    listName: 'U.S. Analyst Focus List - Healthcare',
    displayName: 'JPMorgan U.S. Analyst Focus List - Healthcare',
    year: 2026,
    sector: 'Healthcare',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'LLY', action: 'buy' },
      { ticker: 'ISRG', action: 'buy' },
      { ticker: 'BSX', action: 'buy' },
      { ticker: 'PODD', action: 'buy' },
      { ticker: 'PTCT', action: 'buy' },
      { ticker: 'TVTX', action: 'buy' },
      { ticker: 'RARE', action: 'buy' },
      { ticker: 'XENE', action: 'buy' },
      { ticker: 'IDYA', action: 'buy' },
      { ticker: 'RVMD', action: 'buy' },
      { ticker: 'ORIC', action: 'buy' },
    ],
  },
  {
    institution: 'JPMorgan',
    listName: 'U.S. Analyst Focus List - Consumer Refresh',
    displayName: 'JPMorgan U.S. Analyst Focus List - Consumer Refresh',
    year: 2026,
    sector: 'Consumer',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'EL', action: 'buy' },
      { ticker: 'TPR', action: 'buy' },
      { ticker: 'HD', action: 'buy' },
      { ticker: 'PHM', action: 'buy' },
      { ticker: 'UAL', action: 'buy' },
      { ticker: 'ULTA', action: 'buy' },
      { ticker: 'NCLH', action: 'buy' },
      { ticker: 'OLLI', action: 'buy' },
      { ticker: 'SN', action: 'buy' },
    ],
  },
  {
    institution: 'JPMorgan',
    listName: 'Top Consumer Stocks for 2026',
    displayName: 'JPMorgan Top Consumer Stocks for 2026',
    year: 2026,
    sector: 'Consumer',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'GM', action: 'buy' },
      { ticker: 'AS', action: 'buy' },
      { ticker: 'MKC', action: 'buy' },
      { ticker: 'BBY', action: 'buy' },
      { ticker: 'AZO', action: 'buy' },
      { ticker: 'DLTR', action: 'buy' },
      { ticker: 'BURL', action: 'buy' },
      { ticker: 'CELH', action: 'buy' },
      { ticker: 'CVNA', action: 'buy' },
      { ticker: 'ACI', action: 'buy' },
    ],
  },
  {
    institution: 'Barclays',
    listName: 'Top U.S. Software Stocks for 2026',
    displayName: 'Barclays Top U.S. Software Stocks for 2026',
    year: 2026,
    sector: 'Software',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'ORCL', action: 'buy' },
      { ticker: 'CRM', action: 'buy' },
      { ticker: 'DOCN', action: 'buy' },
    ],
  },
  {
    institution: 'Piper Sandler',
    listName: 'Macro Select Bargain Stocks for 2026',
    displayName: 'Piper Sandler Macro Select Bargain Stocks for 2026',
    year: 2026,
    theme: 'Bargain Stocks',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'GHC', action: 'buy' },
      { ticker: 'EAT', action: 'buy' },
      { ticker: 'PARR', action: 'buy' },
      { ticker: 'DLX', action: 'buy' },
      { ticker: 'MWA', action: 'buy' },
      { ticker: 'KRC', action: 'buy' },
      { ticker: 'UGI', action: 'buy' },
      { ticker: 'CWEN', action: 'buy' },
    ],
  },
  {
    institution: 'Goldman Sachs',
    listName: 'U.S. Conviction List March Additions',
    displayName: 'Goldman Sachs U.S. Conviction List March Additions',
    period: 'March 2026',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'COP', action: 'addition' },
      { ticker: 'LOAR', action: 'addition' },
    ],
  },
  {
    institution: 'Goldman Sachs',
    listName: 'U.S. Conviction List DoorDash Addition',
    displayName: 'Goldman Sachs U.S. Conviction List DoorDash Addition',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'DASH', action: 'addition' },
    ],
  },
  {
    institution: 'Goldman Sachs',
    listName: 'U.S. Conviction List UnitedHealth Addition',
    displayName: 'Goldman Sachs U.S. Conviction List UnitedHealth Addition',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'UNH', action: 'addition' },
    ],
  },
  {
    institution: 'Goldman Sachs',
    listName: 'Software Buy/Sell Coverage List',
    displayName: 'Goldman Sachs Software Buy/Sell Coverage List',
    year: 2026,
    sector: 'Software',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_review',
    importedFrom: '2026_seed',
    members: [
      { ticker: 'MSFT', action: 'buy' },
      { ticker: 'ORCL', action: 'buy' },
      { ticker: 'NOW', action: 'buy' },
      { ticker: 'ADBE', action: 'sell' },
      { ticker: 'DDOG', action: 'sell' },
    ],
  },
]

export const PARTIAL_CANDIDATES: PartialCandidate[] = [
  {
    institution: 'Goldman Sachs',
    listName: 'Rule of 10 Secular Growth Screen',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 10,
  },
  {
    institution: 'Goldman Sachs',
    listName: 'TMT Conviction List Top Picks',
    year: 2026,
    sector: 'TMT',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
  },
  {
    institution: 'JPMorgan',
    listName: '47 Top Stock Picks for 2026',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 47,
  },
  {
    institution: 'Morgan Stanley',
    listName: '14 Stocks for 4 Themes Defining 2026',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 14,
  },
  {
    institution: 'Oppenheimer',
    listName: 'Best-of-Best 12 SMID Stocks',
    year: 2026,
    sector: 'SMID',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 12,
  },
  {
    institution: 'Piper Sandler',
    listName: '13 Contrarian Consumer Stocks',
    year: 2026,
    sector: 'Consumer',
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 13,
  },
  {
    institution: 'Citi',
    listName: 'Top 3 Sectors for 2026 + 3 Picks Each',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
  },
  {
    institution: 'UBS',
    listName: '26 U.S. Stocks to Watch in 2026',
    year: 2026,
    sourceType: 'media_summary',
    confidence: 'needs_review',
    reviewStatus: 'needs_extraction',
    visibleTickers: [],
    expectedCount: 26,
  },
]
